apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xiyouji
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx
  rules:
    - host: xiyouji.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: xiyouji
                port:
                  name: http
